hl.env("TZDIR", "/etc/zoneinfo")
hl.env("GTK_IM_MODULE", "fcitx")
hl.env("QT_IM_MODULE", "wayland;fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("GLFW_IM_MODULE", "ibus")